Switched over to having AWS credentials in config.ini.

diff --git a/bin/aws b/bin/aws
--- a/bin/aws
+++ b/bin/aws
@@ -8,10 +8,32 @@
 # Errors are fatal
 set -e
 
-export AWS_CONFIG_FILE=$(dirname $0)/../aws-credentials.txt
+# 
+# Grab our credentials from config.ini
+#
+pushd $(dirname $0)/.. > /dev/null
+export AWS_ACCESS_KEY_ID=$(cat ./config.ini | grep aws_access_key_id | cut -d= -f2 | awk '{print $1}')
+export AWS_SECRET_ACCESS_KEY=$(cat ./config.ini | grep aws_secret_access_key | cut -d= -f2 | awk '{print $1}')
+popd > /dev/null
+
+if test ! "$AWS_ACCESS_KEY_ID"
+then
+	echo "! "
+	echo "! Unable to load AWS_ACCESS_KEY_ID. Please check your config.ini file."
+	echo "! "
+	exit 1
+fi
+
+if test ! "$AWS_SECRET_ACCESS_KEY"
+then
+	echo "! "
+	echo "! Unable to load AWS_SECRET_ACCESS_KEY. Please check your config.ini file."
+	echo "! "
+	exit 1
+fi
 
 echo "# " >&2
-echo "# Executing aws with these credentials: $AWS_CONFIG_FILE" >&2
+echo "# Executing aws..." >&2
 echo "# " >&2
 
 aws $@
